version: "3.9"

services:
  postgers:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: volunteer
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgers_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgers_data:
