// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volunteer.Infrastructure.Persistence;

#nullable disable

namespace Volunteer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222131703_AddDeliveryAnimalsTable")]
    partial class AddDeliveryAnimalsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Volunteer.Domain.Entities.Animals.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdopterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("adopter_profile_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("breed");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MedicalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("medical_status");

                    b.Property<string>("MicrochipId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("microchip_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_organization_id");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("species");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("Sterilized")
                        .HasColumnType("boolean")
                        .HasColumnName("sterilized");

                    b.PrimitiveCollection<List<string>>("Traits")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("traits");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("Vaccinations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("vaccinations");

                    b.Property<Guid>("VolunteerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_animals");

                    b.HasIndex("AdopterProfileId")
                        .HasDatabaseName("ix_animals_adopter_profile_id");

                    b.HasIndex("VolunteerProfileId")
                        .HasDatabaseName("ix_animals_volunteer_profile_id");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Animals.AnimalPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_animal_photos");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_animal_photos_animal_id");

                    b.ToTable("animal_photos", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<Guid?>("AssignedVolunteerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_volunteer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("Requirements")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("requirements");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.DeliveryAnimal", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.HasKey("DeliveryId", "AnimalId")
                        .HasName("pk_delivery_animals");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_delivery_animals_animal_id");

                    b.ToTable("delivery_animals", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.DeliveryLeg", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<DateTimeOffset?>("DropoffTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dropoff_time");

                    b.Property<DateTimeOffset?>("PickupTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("DeliveryId", "Index")
                        .HasName("pk_delivery_legs");

                    b.ToTable("delivery_legs", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_documents_animal_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Profiles.AdopterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("availability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Experience")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("experience");

                    b.Property<string>("FamilyInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("family_info");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_adopter_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_adopter_profiles_user_id");

                    b.ToTable("adopter_profiles", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Profiles.VolunteerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("integer")
                        .HasColumnName("availability_status");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("CompletedTripsCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_trips_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.PrimitiveCollection<List<string>>("SpeciesAllowed")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("species_allowed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_volunteer_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_volunteer_profiles_user_id");

                    b.ToTable("volunteer_profiles", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Animals.Animal", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Profiles.AdopterProfile", "AdopterProfile")
                        .WithMany("Animals")
                        .HasForeignKey("AdopterProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_animals_adopter_profiles_adopter_profile_id");

                    b.HasOne("Volunteer.Domain.Entities.Profiles.VolunteerProfile", "VolunteerProfile")
                        .WithMany()
                        .HasForeignKey("VolunteerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animals_volunteer_profiles_volunteer_profile_id");

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("current_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("current_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("current_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("current_location_region");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId")
                                .HasConstraintName("fk_animals_animals_id");
                        });

                    b.Navigation("AdopterProfile");

                    b.Navigation("CurrentLocation");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Animals.AnimalPhoto", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Animals.Animal", null)
                        .WithMany("Photos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_animal_photos_animals_animal_id");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.Delivery", b =>
                {
                    b.OwnsOne("Volunteer.Domain.ValueObjects.TimeWindow", "DropoffWindow", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dropoff_from");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dropoff_to");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "FromLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("from_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("from_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_region");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.TimeWindow", "PickupWindow", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("pickup_from");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("pickup_to");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "ToLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("to_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("to_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_region");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.Navigation("DropoffWindow");

                    b.Navigation("FromLocation");

                    b.Navigation("PickupWindow");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.DeliveryAnimal", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Animals.Animal", "Animal")
                        .WithMany("DeliveryAnimals")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_animals_animals_animal_id");

                    b.HasOne("Volunteer.Domain.Entities.Deliveries.Delivery", "Delivery")
                        .WithMany("DeliveryAnimals")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_animals_deliveries_delivery_id");

                    b.Navigation("Animal");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.DeliveryLeg", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Deliveries.Delivery", null)
                        .WithMany("Legs")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_legs_deliveries_delivery_id");

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "FromLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryLegDeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("delivery_id");

                            b1.Property<int>("DeliveryLegIndex")
                                .HasColumnType("integer")
                                .HasColumnName("index");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("from_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("from_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("from_location_region");

                            b1.HasKey("DeliveryLegDeliveryId", "DeliveryLegIndex");

                            b1.ToTable("delivery_legs");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryLegDeliveryId", "DeliveryLegIndex")
                                .HasConstraintName("fk_delivery_legs_delivery_legs_delivery_id_index");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "ToLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryLegDeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("delivery_id");

                            b1.Property<int>("DeliveryLegIndex")
                                .HasColumnType("integer")
                                .HasColumnName("index");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("to_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("to_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_location_region");

                            b1.HasKey("DeliveryLegDeliveryId", "DeliveryLegIndex");

                            b1.ToTable("delivery_legs");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryLegDeliveryId", "DeliveryLegIndex")
                                .HasConstraintName("fk_delivery_legs_delivery_legs_delivery_id_index");
                        });

                    b.Navigation("FromLocation");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Documents.Document", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Animals.Animal", null)
                        .WithMany("Documents")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_animals_animal_id");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Organizations.Organization", b =>
                {
                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_region");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("contact_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("contact_phone");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Profiles.AdopterProfile", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Volunteer.Domain.Entities.Profiles.AdopterProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adopter_profiles_users_user_id");

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "Address", b1 =>
                        {
                            b1.Property<Guid>("AdopterProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_region");

                            b1.HasKey("AdopterProfileId");

                            b1.ToTable("adopter_profiles");

                            b1.WithOwner()
                                .HasForeignKey("AdopterProfileId")
                                .HasConstraintName("fk_adopter_profiles_adopter_profiles_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Profiles.VolunteerProfile", b =>
                {
                    b.HasOne("Volunteer.Domain.Entities.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Volunteer.Domain.Entities.Profiles.VolunteerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volunteer_profiles_users_user_id");

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Contact", "EmergencyContact", b1 =>
                        {
                            b1.Property<Guid>("VolunteerProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("emergency_contact_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("emergency_contact_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("emergency_contact_phone");

                            b1.HasKey("VolunteerProfileId");

                            b1.ToTable("volunteer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerProfileId")
                                .HasConstraintName("fk_volunteer_profiles_volunteer_profiles_id");
                        });

                    b.OwnsOne("Volunteer.Domain.ValueObjects.Location", "HomeBaseLocation", b1 =>
                        {
                            b1.Property<Guid>("VolunteerProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("home_base_location_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("home_base_location_city");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("home_base_location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("home_base_location_longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("home_base_location_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("home_base_location_region");

                            b1.HasKey("VolunteerProfileId");

                            b1.ToTable("volunteer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerProfileId")
                                .HasConstraintName("fk_volunteer_profiles_volunteer_profiles_id");
                        });

                    b.Navigation("EmergencyContact");

                    b.Navigation("HomeBaseLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Animals.Animal", b =>
                {
                    b.Navigation("DeliveryAnimals");

                    b.Navigation("Documents");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Deliveries.Delivery", b =>
                {
                    b.Navigation("DeliveryAnimals");

                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Volunteer.Domain.Entities.Profiles.AdopterProfile", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
